/*
 * jpnCellMatchDone.java
 *
 * Created on 14 août 2008, 15:46
 */
package bbos.General.Views.Match;

import bbos.General.Model.mMatch;
import bbos.General.Model.mTeam;
import bbos.General.Views.Team.jdgTeam;
import bbos.General.Views.Team.jtmTeamPlayers;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author  root
 */
public class jpnCellMatchDone extends javax.swing.JPanel
{

    mMatch _match;
    mTeam _team;

    /** Creates new form jpnCellMatchDone */
    public jpnCellMatchDone(int number, mMatch match,mTeam team)
    {
        initComponents();

        _match = match;
        if (number % 2 == 0)
        {
            this.setBackground(Color.WHITE);
        }
        if (_match.getWinnerId() == _match.getOpponentId())
        {
            jlbIcon.setIcon(new ImageIcon(getClass().getResource("/resources/images/icons/match/lost_little.png")));
            jlbMatchDescription.setText("You have been defeated " + _match.getScore() + " by " + _match.getOppponent().getName() + ".");
        }
        else if (_match.getWinnerId() == 0)
        {
            jlbIcon.setIcon(new ImageIcon(getClass().getResource("/resources/images/icons/match/drawn_little.png")));
            jlbMatchDescription.setText("You have drawn " + _match.getScore() + " with " + _match.getOppponent().getName() + ".");
        }
        else
        {
            jlbIcon.setIcon(new ImageIcon(getClass().getResource("/resources/images/icons/match/victory_little.png")));
            jlbMatchDescription.setText("You have won " + _match.getScore() + " agains " + _match.getOppponent().getName() + ".");
        }
        _team=team;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jlbMatchDescription = new javax.swing.JLabel();
        jlbIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtTeamName = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.acceleratorSelectionForeground"), 1, true));
        setPreferredSize(new java.awt.Dimension(310, 60));
        setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jlbMatchDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbMatchDescription.setText("Victory 1-0 against");
        jPanel2.add(jlbMatchDescription, java.awt.BorderLayout.CENTER);

        jlbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons/match/victory_little.png"))); // NOI18N
        jlbIcon.setMaximumSize(new java.awt.Dimension(34, 30));
        jlbIcon.setMinimumSize(new java.awt.Dimension(34, 30));
        jlbIcon.setPreferredSize(new java.awt.Dimension(34, 30));
        jPanel2.add(jlbIcon, java.awt.BorderLayout.LINE_START);

        add(jPanel2);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jbtTeamName.setText("See opponent");
        jbtTeamName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtTeamNameActionPerformed(evt);
            }
        });
        jPanel1.add(jbtTeamName);

        jButton1.setText("Match details");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents
    private void jbtTeamNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtTeamNameActionPerformed
    {//GEN-HEADEREND:event_jbtTeamNameActionPerformed
        jdgTeam window = new jdgTeam(_match.getOppponent(), jtmTeamPlayers.FULL_VIEW);
        window.setVisible(true);
               
    }//GEN-LAST:event_jbtTeamNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
    jdgMatchDone window=new jdgMatchDone(_match,_team);
    window.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtTeamName;
    private javax.swing.JLabel jlbIcon;
    private javax.swing.JLabel jlbMatchDescription;
    // End of variables declaration//GEN-END:variables
    public void paint(Graphics g)
    {
        super.paint(g);


    }
}
