/*
 * jfCommunicationSettings.java
 *
 * Created on 11 mai 2008, 16:43
 */
package bbos.General.Views;

import bbos.*;
import javax.swing.*;
import java.awt.*;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import bbos.Tools.sdLang;
import bbos.Tools.sdSettings;

/**
 *
 * @author  frederic
 */
public class jdgLogon extends JDialog {

    private static jdgLogon _singleton = null;
    ImageIcon[] images;
    String[] Strings = {"Français", "English"};

    public static String _login;
    public static String _password;
    public static String _webservice;
    
    /** Creates new form jfCommunicationSettings */
    private jdgLogon() {
        initComponents();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        images = new ImageIcon[Strings.length];
        images[0] = createImageIcon("/resources/images/lang/fr.png");
        images[1] = createImageIcon("/resources/images/lang/uk.png");

        cbrFlags cbr = new cbrFlags(images, Strings, this);
        jcbFlags.setModel(new DefaultComboBoxModel(Strings));
        jcbFlags.setRenderer(cbr);
        jcbFlags.addActionListener(cbr);

        jpfPasword.setText(sdSettings.getSingleton().getProperty("password"));
        jtfLogin.setText(sdSettings.getSingleton().getProperty("login"));
        jtfServiceURL.setText(sdSettings.getSingleton().getProperty("communication"));
        jcbFlags.setSelectedItem(sdSettings.getSingleton().getProperty("language"));

        repaint();
    }

    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = JFrame.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbCommunication = new javax.swing.JLabel();
        jtfServiceURL = new javax.swing.JTextField();
        jbtCancel = new javax.swing.JButton();
        jbtOK = new javax.swing.JButton();
        jtfLogin = new javax.swing.JTextField();
        jlbLogin = new javax.swing.JLabel();
        jlbPassword = new javax.swing.JLabel();
        jpfPasword = new javax.swing.JPasswordField();
        jcbFlags = new javax.swing.JComboBox();
        jlbLanguage = new javax.swing.JLabel();
        jcbRememberMe = new javax.swing.JCheckBox();

        setTitle("Communication settings");
        setModal(true);
        setResizable(false);
        setUndecorated(true);

        jlbCommunication.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbCommunication.setText("Communication settings :");

        jtfServiceURL.setText("http://localhost/service.php?wsdl");
        jtfServiceURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfServiceURLActionPerformed(evt);
            }
        });

        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });

        jtfLogin.setText("lord bojo");
        jtfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLoginActionPerformed(evt);
            }
        });

        jlbLogin.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbLogin.setText("Login : ");

        jlbPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbPassword.setText("Password : ");

        jpfPasword.setText("lancie");

        jcbFlags.setMaximumSize(new java.awt.Dimension(220, 70));
        jcbFlags.setMinimumSize(new java.awt.Dimension(220, 70));
        jcbFlags.setPreferredSize(new java.awt.Dimension(220, 70));

        jlbLanguage.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbLanguage.setText("Language : ");

        jcbRememberMe.setText("Remember me");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtOK)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfLogin))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpfPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbRememberMe))
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbFlags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbCommunication, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfServiceURL, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCommunication)
                    .addComponent(jtfServiceURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbLogin)
                    .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPassword)
                    .addComponent(jpfPasword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbRememberMe)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFlags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbLanguage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCancel)
                    .addComponent(jbtOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jtfServiceURLActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfServiceURLActionPerformed
    {//GEN-HEADEREND:event_jtfServiceURLActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtfServiceURLActionPerformed

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtOKActionPerformed
    {//GEN-HEADEREND:event_jbtOKActionPerformed
        if (jcbRememberMe.isSelected()) {
            sdSettings.getSingleton().setProperty("login", jtfLogin.getText());
            sdSettings.getSingleton().setProperty("password", new String(jpfPasword.getPassword()));
            sdSettings.getSingleton().setProperty("communication", jtfServiceURL.getText());
            sdSettings.getSingleton().setProperty("language", (String) jcbFlags.getSelectedItem());
            sdSettings.getSingleton().saveProperties();
        }

       
        if (isValidUser()) {
            this.dispose();
            this.setVisible(false);
        } else {
            this.setVisible(true);
            JOptionPane.showMessageDialog(this, "Unable to connect. Wrong Login, Password or URL.", "Connection Error", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_jbtOKActionPerformed

    private void jtfLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfLoginActionPerformed
    {//GEN-HEADEREND:event_jtfLoginActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtfLoginActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtCancelActionPerformed
    {//GEN-HEADEREND:event_jbtCancelActionPerformed
        System.exit(0);
}//GEN-LAST:event_jbtCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtOK;
    private javax.swing.JComboBox jcbFlags;
    private javax.swing.JCheckBox jcbRememberMe;
    private javax.swing.JLabel jlbCommunication;
    private javax.swing.JLabel jlbLanguage;
    private javax.swing.JLabel jlbLogin;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JPasswordField jpfPasword;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JTextField jtfServiceURL;
    // End of variables declaration//GEN-END:variables
    public static jdgLogon getSingleton() {
        if (_singleton == null) {
            _singleton = new jdgLogon();
        }
        return _singleton;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);

        jlbCommunication.setText(sdLang.getSingleton().getResource("Communication settings") + " :");
        jlbLanguage.setText(sdLang.getSingleton().getResource("Language") + " :");
        jlbLogin.setText(sdLang.getSingleton().getResource("Login") + " :");
        jlbPassword.setText(sdLang.getSingleton().getResource("Password") + " :");
        jcbRememberMe.setText(sdLang.getSingleton().getResource("Remember me") + " :");
        jbtOK.setText(sdLang.getSingleton().getResource("OK"));
        jbtCancel.setText(sdLang.getSingleton().getResource("Cancel"));

    }

    /**
     * @todo Complete with webservice
     * @return
     */
    public boolean isValidUser() {
        try {
            webbos.webbos.Webbos soap = new webbos.webbos.Webbos(new URL(jtfServiceURL.getText()), new QName("http://Webbos/Webbos", "Webbos"));
            int result =soap.getWebbosPort().isValidUser(jtfLogin.getText(), new String(jpfPasword.getPassword()));
            _webservice=jtfServiceURL.getText();
            _login=jtfLogin.getText();
            _password=new String(jpfPasword.getPassword());
            return result == 1;
        } catch (MalformedURLException e) {
            e.printStackTrace();
            return false;
        }
    }
}

