
package webbos.webbos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
//@WebServiceClient(name = "Webbos", targetNamespace = "http://Webbos/Webbos", wsdlLocation = "http://bbos.ainpacte.org/service_test.php?wsdl")
@WebServiceClient(name = "Webbos", targetNamespace = "http://Webbos/Webbos", wsdlLocation = "http://localhost/service_test.php?wsdl")
public class Webbos
    extends Service
{

    private final static URL WEBBOS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            //url = new URL("http://bbos.ainpacte.org/service_test.php?wsdl");
            url = new URL("http://localhost/service_test.php?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WEBBOS_WSDL_LOCATION = url;
    }

    public Webbos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Webbos() {
        super(WEBBOS_WSDL_LOCATION, new QName("http://Webbos/Webbos", "Webbos"));
    }

    /**
     * 
     * @return
     *     returns WebbosPortType
     */
    @WebEndpoint(name = "WebbosPort")
    public WebbosPortType getWebbosPort() {
        return (WebbosPortType)super.getPort(new QName("http://Webbos/Webbos", "WebbosPort"), WebbosPortType.class);
    }

}
