/*
 * jdgBuyStaff.java
 *
 * Created on 13 août 2008, 17:13
 */
package bbos.General.Views.MyBBoS;

import bbos.General.Model.mPlayer;
import bbos.General.Model.mPlayerType;
import bbos.General.Model.mTeam;
import bbos.mBBoS;
import java.awt.DisplayMode;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.TableColumn;

/**
 *
 * @author  root
 */
public class jdgBuyPlayer extends javax.swing.JDialog {

    mTeam _team;
    int _remaining_treasury;
    mPlayer _newPlayer;
    String _name;
    int _number;

    /** Creates new form jdgBuyStaff */
    public jdgBuyPlayer(mTeam team) {

        initComponents();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        _team = team;
        _remaining_treasury = _team.getTreasury();
        _name = "";
        if (_team.getAvailableNumbers().size() > 0) {
            _number = (Integer) _team.getAvailableNumbers().get(0);
        } else {
            _number = 0;
        }

        Vector available_positions = _team.getAvailablePositions(_remaining_treasury);
        available_positions.add(0, "");
        jcbAvailablePostion.setModel(new DefaultComboBoxModel(available_positions));
        jcbAvailablePostion.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                Vector available_type = _team.getAvailablePlayersTypes();
                if (jcbAvailablePostion.getSelectedItem().equals("")) {
                    _newPlayer = null;
                } else {
                    for (int i = 0; i < available_type.size(); i++) {
                        mPlayerType type = (mPlayerType) available_type.get(i);
                        String selection = (String) jcbAvailablePostion.getSelectedItem();
                        if (type.getPosition().equals(selection)) {
                            _newPlayer = new mPlayer(_name, type, _number);
                        }
                    }
                }
                repaint();
            }
        });

        Vector available_numbers = _team.getAvailableNumbers();
        jcbAvailableNumber.setModel(new DefaultComboBoxModel(available_numbers));
        jcbAvailableNumber.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                _number = (Integer) jcbAvailableNumber.getSelectedItem();
                if (_newPlayer != null) {
                    _newPlayer.setNumber(_number);
                }
                repaint();
            }
        });

        jtfName.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                _name = jtfName.getText();
                if (_newPlayer != null) {
                    _newPlayer.setName(_name);
                }
                repaint();
            }
        });

        jtfName.addFocusListener(new FocusListener() {

            public void focusGained(FocusEvent e) {
            }

            public void focusLost(FocusEvent e) {
                _name = jtfName.getText();
                if (_newPlayer != null) {
                    _newPlayer.setName(_name);
                }
                repaint();
            }
        });

        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbTreasury = new javax.swing.JLabel();
        jtfTreasury = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbNewPlayer = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jlbEmpty2 = new javax.swing.JLabel();
        jlbEmpty3 = new javax.swing.JLabel();
        jlbPrice = new javax.swing.JLabel();
        jtfCost = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jlbAvailablePosition = new javax.swing.JLabel();
        jcbAvailablePostion = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jlbAvailableNumber = new javax.swing.JLabel();
        jcbAvailableNumber = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jlbNewName = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 250));
        setModal(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Treasury"));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jlbTreasury.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbTreasury.setText("Remaining treasury :");
        jPanel1.add(jlbTreasury);

        jtfTreasury.setEditable(false);
        jPanel1.add(jtfTreasury);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Player"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 50));

        jtbNewPlayer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbNewPlayer);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));
        jPanel8.add(jlbEmpty2);
        jPanel8.add(jlbEmpty3);

        jlbPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbPrice.setText("Price :");
        jPanel8.add(jlbPrice);

        jtfCost.setEditable(false);
        jtfCost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCost.setText("0");
        jPanel8.add(jtfCost);

        jPanel5.add(jPanel8, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(3, 0));

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jlbAvailablePosition.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbAvailablePosition.setText("Available position :");
        jPanel4.add(jlbAvailablePosition);

        jcbAvailablePostion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jcbAvailablePostion);

        jPanel7.add(jPanel4);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jlbAvailableNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbAvailableNumber.setText("Available number :");
        jPanel6.add(jlbAvailableNumber);

        jcbAvailableNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(jcbAvailableNumber);

        jPanel7.add(jPanel6);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jlbNewName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbNewName.setText("Available number :");
        jPanel9.add(jlbNewName);

        jtfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jtfName);

        jPanel7.add(jPanel9);

        jPanel2.add(jPanel7, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });

        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(580, Short.MAX_VALUE)
                .addComponent(jbtCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtOK)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtOK)
                    .addComponent(jbtCancel))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        if (_newPlayer != null) {
            if (_newPlayer.getName().equals("")) {
                JOptionPane.showMessageDialog(this, "No name defined !");
            } else {
                if (_number == 0) {
                    JOptionPane.showMessageDialog(this, "No number defined !");
                } else {
                    int option = JOptionPane.showConfirmDialog(this, "You will buy a " + _newPlayer.getPosition() + ". Are you sure ?", "Buy Player", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION);
                    if (option == JOptionPane.YES_OPTION) {
                        _team.setTreasury(_remaining_treasury - _newPlayer.getPlayerType().getCost());

                        mBBoS.getSingleton().addNewPlayer(_team, _newPlayer);
                        mBBoS.getSingleton().updateTeam(_team);
                        _team.getPlayers().put(_number, _newPlayer);
                        this.setVisible(false);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No player defined !");
        }
       
    }//GEN-LAST:event_jbtOKActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtOK;
    private javax.swing.JComboBox jcbAvailableNumber;
    private javax.swing.JComboBox jcbAvailablePostion;
    private javax.swing.JLabel jlbAvailableNumber;
    private javax.swing.JLabel jlbAvailablePosition;
    private javax.swing.JLabel jlbEmpty2;
    private javax.swing.JLabel jlbEmpty3;
    private javax.swing.JLabel jlbNewName;
    private javax.swing.JLabel jlbPrice;
    private javax.swing.JLabel jlbTreasury;
    private javax.swing.JTable jtbNewPlayer;
    private javax.swing.JTextField jtfCost;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfTreasury;
    // End of variables declaration//GEN-END:variables
    public void paint(Graphics g) {
        super.paint(g);

        jtbNewPlayer.setModel(new jtmNewPlayer(_newPlayer));
        jtbNewPlayer.setDefaultRenderer(String.class, new jtcNewPlayer(_newPlayer));
        jtbNewPlayer.setDefaultRenderer(Integer.class, new jtcNewPlayer(_newPlayer));

        for (int i = 0; i < jtbNewPlayer.getModel().getColumnCount(); i++) {
            TableColumn column = jtbNewPlayer.getColumnModel().getColumn(i);
            switch (i) {
                case 0:
                    column.setPreferredWidth(80);
                    break;
                case 1:
                    column.setPreferredWidth(15);
                    break;
                case 2:
                    column.setPreferredWidth(15);
                    break;
                case 3:
                    column.setPreferredWidth(15);
                    break;
                case 4:
                    column.setPreferredWidth(15);
                    break;
                case 5:
                    column.setPreferredWidth(240);
                    break;
            }
        }

        int treasury = _remaining_treasury;
        if (_newPlayer != null) {
            treasury = treasury - _newPlayer.getPlayerType().getCost();
            jtfCost.setText(((Integer) _newPlayer.getPlayerType().getCost()).toString());
        } else {
            jtfCost.setText("0");
        }
        jtfTreasury.setText(Integer.toString(treasury));
    }
    }
